### ISSUE TITLE
Inconsistency between what is told and what is written.

### ISSUE THREAD

**Issue by rfmac-inspectos** [AmadeusITGroup/Moire-Pattern-Detection#11]
In the `train.py` script there's the following piece of code:

``` python
# read all images, convert to float, divide by 255 (leads to gray range 0..1), reshape into a row vector
# write class 1 for positive and 0 for negative samples    
sampleIndex = readImageSet(positiveImageFiles, positiveTrainImagePath, X_LL, X_LH, X_HL, X_HH, X_index, Y, sampleIndex, 0)
print('positive data loaded.')

sampleIndex += readImageSet(negativeImageFiles, negativeTrainImagePath, X_LL, X_LH, X_HL, X_HH, X_index, Y, sampleIndex, 1)
print('negative data loaded.')
```

Then there's 2 point of inconsistencies:
1. Actually the values of the images are not divided by 255, but rescaled by MinMaxScaler.
    - It is slightly different, but this way it is dependent of the values present on the images of the dataset.
    - Is this side effect desired?
1. The comment says that class 1 is for the positive samples and class 0 is for the negative samples.
    - This makes sense, but it's implemented inversed, that is, 0 for positives and 1 for negatives.
    - I think that this may lead to the same results, since it is a binary classification. But I would like to know if there was a reason for this change or was it just a misunderstood?

Thank you in advance for the attention.

**Comment by eldhoabraham** [comment]
1. Please note, MinMaxScaler is used on Wavelet images. Its not the input image. And it is scaled between -1 and 1.
2. Documentation Corrected.
