### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by mohtashim-nawaz** [AmadeusITGroup/Moire-Pattern-Detection#14]
Even after scaling images to WIDTH, HEIGHT, Training is not possible. Keeps showing sam error.

**Comment by JaninaPa** [comment]
Have you found a solution? Encountering the same error even after resizing.

**Comment by mohtashim-nawaz** [comment]
Yes Actually read the README again. I have had my request committed, with all neccessary changes.

**Comment by JaninaPa** [comment]
Still can't seem to find the source of the error. What exactly are you referring to?

**Comment by eldhoabraham** [comment]
The CNN network is tuned to work with certain image size.
@mohtashim-nawaz is referring to **Note - Resize Images to WIDTH = 1000 and HEIGHT = 750** in the README

**Comment by JaninaPa** [comment]
@eldhoabraham I have resized the original images to WIDTH = 1000 and HEIGHT = 750
