### ISSUE TITLE
Can you share your model ?

### ISSUE THREAD

**Issue by hieubkset** [AmadeusITGroup/Moire-Pattern-Detection#16]
Can you share your model (moirePattern3CNN_.h5) to email hieubkset@gmail.com. Thanks!

**Comment by linjingxu** [comment]
@hieubkset Hello, have you got the pre-trained model (moirePattern3CNN_.h5) yet?

**Comment by eldoabrahm** [comment]
Sorry for the late response.
The model was trained on private dataset and cant be shared as per GDPR.
