### ISSUE TITLE
Some places are inconsistent with the paper

### ISSUE THREAD

**Issue by Zhangts98** [AmadeusITGroup/Moire-Pattern-Detection#18]
The original paper uses three channels, and your code uses four channels. In the original paper, C2, C3 and C4 use 16 kernels of size 3 x 3 with a stride of 1 pixel, and your C5 and C6 use 32 kernels. The paper uses one dropopt, and your code uses three.
Will the effect of these changes be better than that of the original paper?
![企业微信截图_16284904862013](https://user-images.githubusercontent.com/61573829/128667584-7a2e6fd4-4899-41b5-b21b-89e0ee5e1844.png)
![企业微信截图_162849052727](https://user-images.githubusercontent.com/61573829/128667614-8def12f2-13f0-43c0-8667-45b1971e353e.png)

**Comment by eldoabrahm** [comment]
Hello Zhang
In the future scope of the paper, I have mentioned about exploration with the 4th input layer which is the HH band from the wavelet decomposition. In the method mentioned in the paper it was ignored to get faster training and better performance during prediction on iOS devices.
The current implementation is not exactly same as the paper but the intuition is same.
So, the more info given to the CNN, the better it would be at prediction.
