### ISSUE TITLE
Can I get your Moirepatten dataset

### ISSUE THREAD

**Issue by xiao-keeplearning** [AmadeusITGroup/Moire-Pattern-Detection#4]
Hi, can you share your Moire patten dataset?

**Comment by eldhoabraham** [comment]
Hi Xiao,
The dataset we used for model creation was a private dataset. So, I'm sorry it cant be shared.
Will check if i come across any public dataset.

**Comment by xiao-keeplearning** [comment]
Thank you very much for the prompt reply.
