### ISSUE TITLE
how about the accuracy of your model?

### ISSUE THREAD

**Issue by yisampi** [AmadeusITGroup/Moire-Pattern-Detection#7]
how about the accuracy of your model?

**Comment by eldhoabraham** [comment]
<img width="781" alt="Screen Shot 2020-03-12 at 1 24 17 AM" src="https://user-images.githubusercontent.com/27273982/76458258-48a87a80-6400-11ea-9ad9-79dc13bfd968.png">
I'm writing a medium article for this. It will show all the details.
