### ISSUE TITLE
training error 

### ISSUE THREAD

**Issue by yisampi** [AmadeusITGroup/Moire-Pattern-Detection#8]
Traceback (most recent call last):
  File "train.py", line 321, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "train.py", line 44, in main
    X_LL, X_LH, X_HL, X_HH, X_index, Y, imageCount = readWaveletData(positiveImagePath, negativeImagePath, positiveTrainImagePath, negativeTrainImagePath)
  File "train.py", line 140, in readWaveletData
    sampleIndex = readImageSet(positiveImageFiles, positiveTrainImagePath, X_LL, X_LH, X_HL, X_HH, X_index, Y, sampleIndex, 0)
  File "train.py", line 99, in readImageSet
    ret = readAndScaleImage(f, '', trainImagePath, X_LL, X_LH, X_HL, X_HH, X_index, Y, sampleIndex, bClass)
  File "train.py", line 82, in readAndScaleImage
    imgVector = imgLL.reshape(1, WIDTH*HEIGHT)
ValueError: cannot reshape array of size 120000 into shape (1,187500)

thanks.

**Comment by pdarulewski** [comment]
I have encountered the same error there

**Comment by nickkimer** [comment]
@yisampi @pdarulewski make sure your images are the correct/samee size -- the scaleData function assumes all your images are of size WIDTH*HEIGHT = 187500
